import { Dict } from '#/api';

export const TableColumn: any = [
  {
    title: '日期',
    field: 'day',
    align: 'center',
    // width: '6%',
    minWidth: 90,
  },
  {
    title: '拌料桶数',
    field: 'bucket_num',
    align: 'center',
    // width: '6%',
    minWidth: 90,
  },
  {
    title: '计划制包',
    field: 'plan',
    headerAlign: 'center',
    children: [
      {
        field: 'plan_num',
        title: '数量',
        align: 'center',
        // width: '6%',
        minWidth: 90,
      },
      {
        field: 'plan_fid',
        title: '配方',
        align: 'center',
        // width: '6%',
        minWidth: 90,
        cellRender: { name: 'dict', code: Dict.KeyEnum.FORMULA },
      },
      {
        field: 'plan_variety_id',
        title: '接种',
        align: 'center',
        // width: '6%',
        minWidth: 90,
        cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CATEGORY },
      },
      {
        field: 'plan_type',
        title: '常规/试验',
        align: 'center',
        // width: '6%',
        cellRender: { name: 'dict', code: Dict.KeyEnum.VACCINATION_TYPE },
        minWidth: 90,
      },
    ],
  },
  {
    title: '实际生产',
    field: 'reality',
    headerAlign: 'center',
    children: [
      {
        field: 'reality_num',
        title: '数量',
        align: 'center',
        // width: '6%',
        minWidth: 90,
      },
      {
        field: 'reality_fid',
        title: '配方',
        // width: '6%',
        minWidth: 90,
        cellRender: { name: 'dict', code: Dict.KeyEnum.FORMULA },
      },
      {
        field: 'variety_id',
        title: '接种',
        // width: '6%',
        minWidth: 90,
        cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CATEGORY },
      },
      {
        field: 'reality_at',
        title: '接种日期',
        align: 'center',
        // width: '6%',
        minWidth: 90,
      },
      {
        field: 'put_num',
        title: '入库',
        align: 'center',
        // width: '6%',
        minWidth: 90,
      },
      {
        field: 'vaccination_num',
        title: '库房接种数量',
        align: 'center',
        // width: '8%',
        minWidth: 120,
      },
    ],
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    // width: '18%',
    minWidth: 270,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    // width: '8%',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
