import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  // {
  //   title: '菌包编号',
  //   field: 'mb_sn',
  //   align: 'center',
  //   minWidth: 135,
  // },
  {
    title: '菌种编号',
    field: 'strain_sn',
    align: 'center',
    minWidth: 135,
  },
  {
    title: '鉴定日期',
    field: 'identification_at',
    align: 'center',
    sortable: true,
    minWidth: 90,
  },
  {
    title: '罐号',
    field: 'can_no',
    align: 'center',
    minWidth: 60,
    sortable: true,
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CAN_NO },
  },
  {
    title: '品种',
    field: 'variety_id',
    align: 'center',
    minWidth: 75,
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CATEGORY },
  },
  {
    title: '培养时间(h)',
    field: 'hour',
    align: 'center',
    minWidth: 75,
    cellRender: { name: 'number' },
  },
  {
    title: 'PH',
    field: 'ph',
    align: 'center',
    minWidth: 60,
    cellRender: { name: 'number' },
  },
  {
    title: '菌丝浓度(ng/g)',
    field: 'concentration',
    align: 'center',
    minWidth: 110,
    cellRender: { name: 'number' },
  },
  {
    title: '判定结果',
    field: 'result',
    align: 'center',
    minWidth: 75,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 165,
  },
  {
    title: '鉴定人员',
    field: 'nickname',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '创建时间',
    field: 'created_at',
    align: 'center',
    minWidth: 90,
    sortable: true,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
