import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', width: '4%', minWidth: 60 },
  {
    title: '制包编号',
    field: 'material_sn',
    align: 'center',
    width: '8%',
    minWidth: 120,
  },
  {
    title: '柜号',
    field: 'material_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.MATERIAL },
    width: '10%',
    minWidth: 150,
  },
  {
    title: '灭菌时间',
    field: 'spec_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.MATERIAL_SPEC },
    width: '7%',
    minWidth: 105,
  },
  {
    title: '实际灭菌时间',
    field: 'manufacturer',
    align: 'center',
    width: '10%',
  },
  {
    title: '灭菌温度',
    field: 'num',
    align: 'center',
    cellRender: { name: 'money' },
    width: '7%',
    minWidth: 105,
  },
  {
    title: '灭菌程序',
    field: 'unit_id',
    align: 'center',
    width: '7%',
    minWidth: 105,
    cellRender: { name: 'dict', code: Dict.KeyEnum.UNIT },
  },
  {
    title: '温度压力',
    field: 'price',
    align: 'center',
    cellRender: { name: 'money' },
    width: '7%',
    minWidth: 105,
  },
  {
    title: '检测人员',
    field: 'nickname',
    align: 'center',
    width: '6%',
    minWidth: 90,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    width: '10%',
    minWidth: 150,
  },
  {
    title: '创建时间',
    field: 'created_at',
    align: 'center',
    width: '8%',
    minWidth: 120,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    width: '8%',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
