export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  {
    title: '菌包编号',
    field: 'mb_sn',
    align: 'center',
    minWidth: 200,
  },
  {
    title: '制包日期',
    field: 'make_at',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '接种日期',
    field: 'vaccination_at',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '品种',
    field: 'variety',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '养菌房',
    field: 'warehouse',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '菌龄',
    field: 'strain_age',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '数量',
    field: 'num',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '金额',
    field: 'amount',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '来源',
    field: 'source',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 150,
  },
  {
    title: '购买日期',
    field: 'pay_at',
    align: 'center',
    minWidth: 150,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
