import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  // {
  //   title: '菌包编号',
  //   field: 'mb_sn',
  //   align: 'center',
  //   minWidth: 135,
  // },
  {
    title: '菌种编号',
    field: 'strain_sn',
    align: 'center',
    minWidth: 135,
  },
  {
    title: '观察日期',
    field: 'observe_at',
    align: 'center',
    minWidth: 105,
    sortable: true,
  },
  {
    title: '罐号',
    field: 'can_no',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CAN_NO },
  },
  {
    title: '品种',
    field: 'variety_id',
    align: 'center',
    minWidth: 105,
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CATEGORY },
  },
  {
    title: '培养时间(h)',
    field: 'hour',
    align: 'center',
    minWidth: 105,
    cellRender: { name: 'number' },
  },
  {
    title: '气味',
    field: 'smell',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '菌种状态',
    field: 'state',
    align: 'center',
    minWidth: 105,
  },
  {
    title: '风速',
    field: 'wind_speed',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '温度(℃)',
    field: 'temperature',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '有无杂菌',
    field: 'varied_id',
    align: 'center',
    minWidth: 105,
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_VARIED },
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 145,
  },
  {
    title: '记录人员',
    field: 'nickname',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
