import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  {
    title: '出菇编号',
    field: 'fruiting_sn',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '菌包编号',
    field: 'mb_sn',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '上架日期',
    field: 'put_at',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '出菇房',
    field: 'room_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.STERILIZER_CABINET },
    minWidth: 90,
  },
  {
    title: '包芯温度(℃)',
    field: 'temperature',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 120,
  },
  {
    title: '上架包数',
    field: 'put_num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 75,
  },
  {
    title: '产量',
    field: 'out_num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 75,
  },
  {
    title: 'A菇率',
    field: 'a_rate',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 75,
  },
  {
    title: '单包产量',
    field: 'sp_num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 75,
  },
  {
    title: '技术员',
    field: 'devName',
    align: 'center',
    minWidth: 75,
  },
  {
    title: '出菇周期',
    field: 'cycle',
    align: 'center',
    minWidth: 75,
  },
  {
    title: '出菇实验',
    field: 'experiment',
    align: 'center',
    minWidth: 75,
  },
  {
    title: '出菇总结',
    field: 'summarize',
    align: 'center',
    minWidth: 75,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 150,
  },
  {
    title: '检测时间',
    field: 'created_at',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
