import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  {
    title: '出菇编号',
    field: 'fruiting_sn',
    align: 'center',
    minWidth: 170,
    slots: { default: 'fruiting_sn' },
  },
  {
    title: '出菇房',
    field: 'room_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.FRUITING_HOUSE },
    minWidth: 100,
  },
  {
    title: '包芯温度',
    field: 'temperature',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 100,
  },
  {
    title: '上架日期',
    field: 'put_at',
    align: 'center',
    minWidth: 110,
  },
  {
    title: '上架包数',
    field: 'put_num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: '产量',
    field: 'out_num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: 'A菇产量',
    field: 'a_out_num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: 'A菇率',
    field: 'a_rate',
    align: 'center',
    cellRender: { name: 'percent' },
    minWidth: 90,
  },
  {
    title: '单包产量/斤',
    field: 'sp_num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 100,
  },
  {
    title: '单包A菇/斤',
    field: 'asp_num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 100,
  },
  {
    title: '技术员',
    field: 'devName',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '下架日期',
    field: 'out_at',
    align: 'center',
    minWidth: 110,
  },
  {
    title: '出菇周期',
    field: 'cycle',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '出菇实验',
    field: 'experiment',
    align: 'center',
    minWidth: 200,
  },
  {
    title: '出菇总结',
    field: 'summarize',
    align: 'center',
    minWidth: 200,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 150,
  },
  {
    title: '创建时间',
    field: 'created_at',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 180,
    fixed: 'right',
    slots: { default: 'action' },
  },
];

export const DetailTableColumn: any = [
  {
    title: '菌包数据',
    field: 'strain_data',
    align: 'center',
    children: [
      {
        title: '菌包编号',
        field: 'mb_sn',
        align: 'center',
        minWidth: 280,
        slots: { default: 'mb_sn' },
      },
      {
        title: '接种日期',
        field: 'vr_at',
        align: 'center',
        minWidth: 95,
      },
      {
        title: '菌龄',
        field: 'strain_age',
        align: 'center',
        minWidth: 60,
      },
      {
        title: '养菌房',
        field: 'warehouse',
        align: 'center',
        minWidth: 90,
      },
      {
        title: '菌种',
        field: 'variety',
        align: 'center',
        minWidth: 90,
      },
      {
        title: '配方',
        field: 'formulaName',
        align: 'center',
        minWidth: 100,
      },
      {
        title: '数量',
        field: 'co_put_num',
        align: 'center',
        minWidth: 100,
      },
    ],
  },
  {
    title: '出菇数据',
    field: 'fruiting_data',
    align: 'center',
    children: [
      {
        title: '出菇编号',
        field: 'fruiting_sn',
        align: 'center',
        minWidth: 140,
      },
      {
        title: '上架时间',
        field: 'put_at',
        align: 'center',
        minWidth: 95,
      },
      {
        title: '下架时间',
        field: 'out_at',
        align: 'center',
        minWidth: 95,
      },
      {
        title: '产量',
        field: 'co',
        align: 'center',
        children: [
          {
            title: '总',
            field: 'co_amount',
            align: 'center',
            minWidth: 90,
            cellRender: { name: 'number' },
          },
          {
            title: 'A菇',
            field: 'co_a_amount',
            align: 'center',
            minWidth: 90,
            cellRender: { name: 'number' },
          },
        ],
      },
      {
        title: 'A菇率',
        field: 'co_a_rate',
        align: 'center',
        minWidth: 75,
        cellRender: { name: 'percent' },
      },
      {
        title: '单包产量/斤',
        field: 'sp',
        align: 'center',
        children: [
          {
            title: '总',
            field: 'co_sp_num',
            align: 'center',
            minWidth: 70,
            cellRender: { name: 'number' },
          },
          {
            title: 'A菇',
            field: 'co_asp_num',
            align: 'center',
            minWidth: 70,
            cellRender: { name: 'number' },
          },
        ],
      },
      {
        title: '技术员',
        field: 'devName',
        align: 'center',
        minWidth: 100,
      },
    ],
  },
  {
    title: '检测数据',
    field: 'check_data',
    align: 'center',
    children: [
      {
        title: '含水率%',
        field: 'moisture',
        align: 'center',
        children: [
          {
            title: '上',
            field: 'upper_moisture',
            align: 'center',
            minWidth: 52,
          },
          {
            title: '中',
            field: 'middle_moisture',
            align: 'center',
            minWidth: 52,
          },
          {
            title: '下',
            field: 'lower_moisture',
            align: 'center',
            minWidth: 52,
          },
        ],
      },
      {
        title: 'PH值',
        field: 'ph',
        align: 'center',
        children: [
          {
            title: '上',
            field: 'upper_ph',
            align: 'center',
            minWidth: 45,
          },
          {
            title: '中',
            field: 'middle_ph',
            align: 'center',
            minWidth: 45,
          },
          {
            title: '下',
            field: 'lower_ph',
            align: 'center',
            minWidth: 45,
          },
        ],
      },
    ],
  },
];
