import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', width: '4%', minWidth: 60 },
  {
    title: '原料编号',
    field: 'material_sn',
    align: 'center',
    width: '8%',
    minWidth: 120,
  },
  {
    title: '检测人员',
    field: 'nickname',
    align: 'center',
    width: '6%',
    minWidth: 90,
  },
  {
    title: '检测时间',
    field: 'detection_at',
    align: 'center',
    width: '8%',
    minWidth: 120,
  },
  {
    title: '原料名称',
    field: 'material_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.MATERIAL },
    width: '10%',
    minWidth: 150,
  },
  {
    title: '检测机器',
    field: 'machine_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.MATERIAL_MACHINE },
    width: '7%',
    minWidth: 105,
  },
  {
    title: '水份',
    field: 'moisture',
    align: 'center',
    width: '7%',
    minWidth: 105,
  },
  {
    title: 'PH',
    field: 'ph',
    align: 'center',
    width: '7%',
    minWidth: 105,
    cellRender: { name: 'dict', code: Dict.KeyEnum.UNIT },
  },
  {
    title: '蛋白含量',
    field: 'protein',
    align: 'center',
    width: '7%',
    minWidth: 105,
  },
  {
    title: '含氮量',
    field: 'nitrogen',
    align: 'center',
    width: '8%',
    minWidth: 120,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    width: '10%',
    minWidth: 150,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    width: '8%',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
