import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  {
    title: '原料编号',
    field: 'material_sn',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '名称',
    field: 'material_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.MATERIAL },
    minWidth: 150,
  },
  {
    title: '规格',
    field: 'spec_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.MATERIAL_SPEC },
    minWidth: 105,
  },
  { title: '购置厂家', field: 'manufacturer', align: 'center', minWidth: 105 },
  {
    title: '数量',
    field: 'num',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 105,
  },
  {
    title: '单位',
    field: 'unit_id',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'dict', code: Dict.KeyEnum.UNIT },
  },
  {
    title: '单价(元)',
    field: 'price',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 105,
  },
  {
    title: '合计金额(元)',
    field: 'amount',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 120,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 155,
  },
  {
    title: '采购人',
    field: 'nickname',
    align: 'center',
    minWidth: 80,
  },
  {
    title: '购置日期',
    field: 'purchase_at',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '入库日期',
    field: 'put_at',
    align: 'center',
    minWidth: 140,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
