import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', width: '4%', minWidth: 60 },
  {
    title: '原料编号',
    field: 'material_sn',
    align: 'center',
    width: '8%',
    minWidth: 120,
  },
  {
    title: '名称',
    field: 'material_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.MATERIAL },
    width: '10%',
    minWidth: 150,
  },
  {
    title: '规格',
    field: 'spec_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.MATERIAL_SPEC },
    width: '7%',
    minWidth: 105,
  },
  { title: '购置厂家', field: 'manufacturer', align: 'center', width: '10%' },
  {
    title: '数量',
    field: 'num',
    align: 'center',
    cellRender: { name: 'money' },
    width: '7%',
    minWidth: 105,
  },
  {
    title: '单位',
    field: 'unit_id',
    align: 'center',
    width: '7%',
    minWidth: 105,
    cellRender: { name: 'dict', code: Dict.KeyEnum.UNIT },
  },
  {
    title: '单价(元)',
    field: 'price',
    align: 'center',
    cellRender: { name: 'money' },
    width: '7%',
    minWidth: 105,
  },
  {
    title: '合计金额(元)',
    field: 'amount',
    align: 'center',
    cellRender: { name: 'money' },
    width: '8%',
    minWidth: 120,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    width: '10%',
    minWidth: 150,
  },
  {
    title: '采购人',
    field: 'nickname',
    align: 'center',
    width: '6%',
    minWidth: 90,
  },
  {
    title: '购置时间',
    field: 'created_at',
    align: 'center',
    width: '8%',
    minWidth: 120,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    width: '8%',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
