import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  {
    title: '菌包编号',
    field: 'mb_sn',
    align: 'center',
    minWidth: 200,
    slots: { default: 'mb_sn' },
  },
  {
    title: '制包日期',
    field: 'make_bag_at',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '配方',
    field: 'formulaName',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '品种',
    field: 'variety_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CATEGORY },
    minWidth: 90,
  },
  {
    title: '罐号',
    field: 'can_no',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CAN_NO },
    minWidth: 90,
  },
  {
    title: '养菌房',
    field: 'warehouse_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_HOUSE },
    minWidth: 90,
  },
  {
    title: '库房位置',
    field: 'location',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '透壁',
    field: 'tw',
    align: 'center',
    minWidth: 100,
  },
  {
    title: '长满',
    field: 'overgrow',
    align: 'center',
    minWidth: 100,
  },
  {
    title: '设备状态',
    field: 'device_state',
    align: 'center',
    minWidth: 120,
    slots: { default: 'device_state' },
  },
  {
    title: '消毒',
    field: 'sterilize',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '入库日期',
    field: 'put_at',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '入库量',
    field: 'put_num',
    align: 'center',
    minWidth: 120,
    cellRender: { name: 'number' },
  },
  {
    title: '出库日期',
    field: 'out_at',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '出库量',
    field: 'out_num',
    align: 'center',
    minWidth: 120,
    cellRender: { name: 'number' },
  },
  {
    title: '记录人员',
    field: 'nickname',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 150,
  },
  // {
  //   title: '创建时间',
  //   field: 'created_at',
  //   align: 'center',
  //   minWidth: 120,
  // },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 180,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
