import { Dict } from '#/api';

export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  // {
  //   title: '制包编号',
  //   field: 'make_bag_sn',
  //   align: 'center',
  //   minWidth: 120,
  // },
  {
    title: '菌包编号',
    field: 'mb_sn',
    align: 'center',
    minWidth: 200,
  },
  {
    title: '接种日期',
    field: 'vaccination_at',
    align: 'center',
    minWidth: 100,
  },
  {
    title: '罐号',
    field: 'can_no',
    align: 'center',
    minWidth: 75,
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CAN_NO },
  },
  {
    title: '接种数量',
    field: 'num',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '品种',
    field: 'variety_id',
    align: 'center',
    cellRender: { name: 'dict', code: Dict.KeyEnum.STRAIN_CATEGORY },
    minWidth: 105,
  },
  {
    title: '菌种量/ml',
    field: 'strain_num',
    align: 'center',
    minWidth: 105,
    cellRender: { name: 'number' },
  },
  {
    title: '破损量',
    field: 'breakage',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '接种室温度',
    field: 'room_temperature',
    align: 'center',
    minWidth: 105,
    cellRender: { name: 'number' },
  },
  {
    title: '菌包PH',
    field: 'ph',
    align: 'center',
    minWidth: 105,
    cellRender: { name: 'number' },
  },
  {
    title: '菌包温度',
    field: 'mb_temperature',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 180,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 110,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
