export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  {
    title: '出菇编号',
    field: 'fruiting_sn',
    align: 'center',
    minWidth: 120,
    slots: { default: 'fruiting_sn' },
  },
  {
    title: '采摘员',
    field: 'name',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '采摘日期',
    field: 'pick_at',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '数量/斤',
    field: 'amount',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: 'A菇数量/斤',
    field: 'a_amount',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: 'A菇率',
    field: 'a_rate',
    align: 'center',
    cellRender: { name: 'percent' },
    minWidth: 90,
  },
  {
    title: 'B菇数量/斤',
    field: 'b_amount',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: 'B菇率',
    field: 'b_rate',
    align: 'center',
    cellRender: { name: 'percent' },
    minWidth: 90,
  },
  {
    title: 'C菇数量/斤',
    field: 'c_amount',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: 'C菇率',
    field: 'c_rate',
    align: 'center',
    cellRender: { name: 'percent' },
    minWidth: 90,
  },
  {
    title: '包数',
    field: 'put_num',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '单包产量/斤',
    field: 'sp_num',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '单包A菇/斤',
    field: 'asp_num',
    align: 'center',
    minWidth: 90,
    cellRender: { name: 'number' },
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 150,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
