export const TableColumn: any = [
  { title: '序号', align: 'center', type: 'seq', minWidth: 60 },
  {
    title: '出菇编号',
    field: 'fruiting_sn',
    align: 'center',
    minWidth: 120,
  },
  {
    title: '采摘员',
    field: 'name',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '采摘日期',
    field: 'pick_at',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '数量/斤',
    field: 'amount',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: 'A菇数量/斤',
    field: 'a_amount',
    align: 'center',
    cellRender: { name: 'number' },
    minWidth: 90,
  },
  {
    title: '备注',
    field: 'remark',
    align: 'center',
    minWidth: 150,
  },
  {
    title: '创建时间',
    field: 'created_at',
    align: 'center',
    minWidth: 90,
  },
  {
    title: '操作',
    field: 'action',
    align: 'center',
    minWidth: 120,
    fixed: 'right',
    slots: { default: 'action' },
  },
];
